default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV["RAILS_MAX_THREADS"] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: taypi_development

test:
  <<: *default
  database: taypi_test

production:
  <<: *default
  database: taypi_production